// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using daytwo.DataHelpers;

namespace daytwo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220218185344_pricesAdded")]
    partial class pricesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("daytwo.Models.Product", b =>
                {
                    b.Property<int>("ProduceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProduceID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            Description = "Oranges",
                            Price = 12
                        },
                        new
                        {
                            ProduceID = 2,
                            Description = "Apples",
                            Price = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
